# Generated by Django 5.0 on 2023-12-25 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='problem',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='problem',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='online_test.question'),
            preserve_default=False,
        ),
    ]
