# Generated by Django 5.0 on 2023-12-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0004_alter_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
