# Generated by Django 5.0 on 2023-12-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0005_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
