# Generated by Django 5.0 on 2023-12-28 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0010_result_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='user',
        ),
    ]
