# Generated by Django 5.0 on 2024-01-20 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[(1, 'teacher'), (0, 'student')], default=0),
        ),
    ]
