# Generated by Django 5.0 on 2024-01-26 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myusers', '0002_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
