# Generated by Django 5.0 on 2023-12-29 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0012_question_course_result_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='course',
            field=models.ForeignKey(default='CS151', on_delete=django.db.models.deletion.CASCADE, to='online_test.test'),
            preserve_default=False,
        ),
    ]
