# Generated by Django 5.0 on 2024-01-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system', '0002_rename_course_description_course_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontent',
            name='module',
            field=models.CharField(),
        ),
    ]
