# Generated by Django 5.0 on 2024-01-20 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system', '0004_coursecontent_quiz_alter_coursecontent_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='course',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
