# Generated by Django 5.0 on 2024-01-26 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system', '0012_rename_course_studentcourse_course_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseforteacher',
            options={'ordering': ['teacher__user__first_name', 'teacher__user__last_name']},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['user__first_name', 'user__last_name']},
        ),
    ]
