# Generated by Django 5.0 on 2024-01-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system', '0013_alter_courseforteacher_options_alter_teacher_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentcourse',
            options={'ordering': ['student__user__first_name', 'student__user__last_name']},
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='file',
            field=models.FileField(blank=True, upload_to='content/'),
        ),
    ]
