# Generated by Django 5.0 on 2024-02-04 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system', '0014_alter_studentcourse_options_alter_coursecontent_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='learning_system.teacher'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courseforteacher',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_system.course'),
        ),
    ]
